#!/bin/bash

soundDisabled() {
    grep -qE "^[ ]*splash.screen.sound[ ]*=[ ]*0[ ]*$" /boot/anbernic-boot.conf
}

do_start ()
{
#    if ls /boot/splash/*.mp4 >/dev/null 2>/dev/null
#    then
#        do_videostart "$(ls /boot/splash/*.mp4 | sed -e "$((RANDOM%$(ls -1 /boot/splash/*.mp4 | wc -l)+1))!d")"
#    elif [[ $(ls /boot/splash/*.{jpg,png}  2>/dev/null) ]]
#    then
#        do_imagestart "$(ls /boot/splash/*.{jpg,png} | sed -e "$((RANDOM%$(ls -1 /boot/splash/*.{jpg,png} | wc -l)+1))!d")"
#    else
#	hdmi_status=$(cat /sys/devices/platform/singleadc-joypad/hdst)
#	[[ "$hdmi_status" == "connected" ]]&&do_videostart "/usr/share/anbernic/splash/splash_1280_720.mp4"||do_videostart "/usr/share/anbernic/splash/splash.mp4"
#    fi
	hdmi_status=$(cat /sys/devices/platform/singleadc-joypad/hdst)
	[[ "$hdmi_status" == "connected" ]]&&do_imagestart "/usr/share/anbernic/splash/logo_hdmi.png"||do_imagestart "/usr/share/anbernic/splash/logo_boot.png"
}

do_imagestart()
{
    image="$1"
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    N=0
    while ! test -e /dev/fb0 -o $N -gt 15
    do
        sleep 1
        let N++
    done
    test -e /dev/fb0 && fbv -f -i "${image}"
    sleep infinity
    wait $!
}

do_videostart ()
{
    video="$1"
    mpv_opt=
    if soundDisabled
    then
        mpv_opt=--no-audio
    fi
    /usr/bin/mpv --no-config $mpv_opt "$video" &
    wait $!
}

case "$1" in
    start)
        grep -qE '^[ ]*splash.screen.enabled[ ]*=[ ]*0[ ]*$' "/boot/anbernic-boot.conf" && exit 0
        do_start &
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
esac

exit $?
