#!/bin/bash

ACTION=$1
shift

do_help() {
    echo "${1} scanlist" >&2
    echo "${1} list" >&2
}

do_list() {
    connmanctl services | sed 's/^...[ ]*//' | awk -F '[ ]*[ ]wifi_[[:alnum:]]*_' '{if (NF==2) print $1}' | sort -u # remove duplicates (a single wifi can appear under 2 interfaces)
}

do_scanlist() {
    connmanctl scan wifi >/dev/null 2>/dev/null
    do_list
}

do_enable() {
    SSID=$1
    PSK=$2

    mkdir -p "/var/lib/connman" || return 1
    cat > "/var/lib/connman/anbernic_wifi.config" <<EOF
[global]
Name=anbernic

[service_anbernic_default]
Type=wifi
Name=${SSID}
EOF
    if test "${PSK}" != ""
    then
	echo "Passphrase=${PSK}" >> "/var/lib/connman/anbernic_wifi.config"
    fi

    connmanctl enable wifi || return 1
    connmanctl scan   wifi || return 1
    return 0
}

do_disable() {
    connmanctl disable wifi
	echo 113 > /sys/class/gpio/export
	GPIO113=$(cat /sys/class/gpio/gpio113/value)
	if [ "$GPIO113" == "1" ];then
		echo out > /sys/class/gpio/gpio113/direction
		echo 0 > /sys/class/gpio/gpio113/value
		echo 113 > /sys/class/gpio/unexport		
	fi
}

do_start() {
    settingsWlan="$(anbernic-settings -command load -key wifi.enabled)"
    if [ "$settingsWlan" != "1" ];then
        return 0
    fi
    connmanctl enable wifi || return 1
    connmanctl scan   wifi || return 1
}

case "${ACTION}" in
    "list")
	do_list
	;;
    "scanlist")
	do_scanlist
	;;
    "start")
	do_start
	;;
    "enable")
	echo 113 > /sys/class/gpio/export
	GPIO113=$(cat /sys/class/gpio/gpio113/value)
	if [ "$GPIO113" == "0" ];then
		echo out > /sys/class/gpio/gpio113/direction
		echo 1 > /sys/class/gpio/gpio113/value
		echo 113 > /sys/class/gpio/unexport
		sleep 2
	fi
	SSID=$1
	PSK=$2
	do_enable "${SSID}" "${PSK}" || exit 1
	;;
    "disable")
	do_disable || exit 1
	;;
    *)
	do_help "${0}"
esac
exit 0
