################################################################################
#
# anbernic.linux System
#
################################################################################

ANBERNIC_SYSTEM_SOURCE=

ANBERNIC_SYSTEM_VERSION = 29
ANBERNIC_SYSTEM_DATE_TIME = $(shell date "+%Y/%m/%d %H:%M")
ANBERNIC_SYSTEM_DEPENDENCIES = tzdata

ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_RPI3),y)
	ANBERNIC_SYSTEM_ARCH=rpi3
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rpi3
	ANBERNIC_SYSTEM_SUBDIR=rpi-firmware
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ROCKPRO64),y)
	ANBERNIC_SYSTEM_ARCH=rockpro64
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rockpro64
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ROCK960),y)
	ANBERNIC_SYSTEM_ARCH=rock960
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rock960
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_TINKERBOARD),y)
	ANBERNIC_SYSTEM_ARCH=tinkerboard
	ANBERNIC_SYSTEM_ANBERNIC_CONF=tinkerboard
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_MIQI),y)
	ANBERNIC_SYSTEM_ARCH=miqi
	ANBERNIC_SYSTEM_ANBERNIC_CONF=miqi
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_LIBRETECH_H5),y)
	ANBERNIC_SYSTEM_ARCH=libretech_h5
	ANBERNIC_SYSTEM_ANBERNIC_CONF=libretech_h5
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ODROIDN2),y)
	ANBERNIC_SYSTEM_ARCH=odroidn2
	ANBERNIC_SYSTEM_ANBERNIC_CONF=odroidn2
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ODROIDGOA),y)
	ANBERNIC_SYSTEM_ARCH=odroidgoa
	ANBERNIC_SYSTEM_ANBERNIC_CONF=odroidgoa
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_XU4),y)
	ANBERNIC_SYSTEM_ARCH=odroidxu4
	ANBERNIC_SYSTEM_ANBERNIC_CONF=xu4
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ODROIDC2),y)
	ANBERNIC_SYSTEM_ARCH=odroidc2
	ANBERNIC_SYSTEM_ANBERNIC_CONF=odroidc2
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_ODROIDC4),y)
	ANBERNIC_SYSTEM_ARCH=odroidc4
	ANBERNIC_SYSTEM_ANBERNIC_CONF=odroidc4
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_S905),y)
	ANBERNIC_SYSTEM_ARCH=s905
	ANBERNIC_SYSTEM_ANBERNIC_CONF=s905
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_S912),y)
	ANBERNIC_SYSTEM_ARCH=s912
	ANBERNIC_SYSTEM_ANBERNIC_CONF=s912
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_X86),y)
	ANBERNIC_SYSTEM_ARCH=x86
	ANBERNIC_SYSTEM_ANBERNIC_CONF=x86
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_X86_64),y)
	ANBERNIC_SYSTEM_ARCH=x86_64
	ANBERNIC_SYSTEM_ANBERNIC_CONF=x86_64
	ANBERNIC_SYSTEM_SUBDIR=
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_RPI2),y)
	ANBERNIC_SYSTEM_ARCH=rpi2
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rpi2
	ANBERNIC_SYSTEM_SUBDIR=rpi-firmware
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_RPI1),y)
	ANBERNIC_SYSTEM_ARCH=rpi1
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rpi1
	ANBERNIC_SYSTEM_SUBDIR=rpi-firmware
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_RPI4),y)
	ANBERNIC_SYSTEM_ARCH=rpi4
	ANBERNIC_SYSTEM_ANBERNIC_CONF=rpi4
	ANBERNIC_SYSTEM_SUBDIR=rpi-firmware
else ifeq ($(BR2_PACKAGE_ANBERNIC_TARGET_VIM3),y)
	ANBERNIC_SYSTEM_ARCH=vim3
	ANBERNIC_SYSTEM_ANBERNIC_CONF=vim3
	ANBERNIC_SYSTEM_SUBDIR=
else
	ANBERNIC_SYSTEM_ARCH=unknown
	ANBERNIC_SYSTEM_ANBERNIC_CONF=unknown
	ANBERNIC_SYSTEM_SUBDIR=
endif

define ANBERNIC_SYSTEM_INSTALL_TARGET_CMDS

	# version/arch
	mkdir -p $(TARGET_DIR)/usr/share/anbernic
	echo -n "$(ANBERNIC_SYSTEM_ARCH)" > $(TARGET_DIR)/usr/share/anbernic/anbernic.arch
	echo $(ANBERNIC_SYSTEM_VERSION) $(ANBERNIC_SYSTEM_DATE_TIME) > $(TARGET_DIR)/usr/share/anbernic/anbernic.version

	# datainit
	mkdir -p $(TARGET_DIR)/usr/share/anbernic/datainit/system
	cp $(BR2_EXTERNAL_ANBERNIC_PATH)/package/anbernic/core/anbernic-system/anbernic.conf $(TARGET_DIR)/usr/share/anbernic/datainit/system

	# anbernic-boot.conf
	$(INSTALL) -D -m 0644 $(BR2_EXTERNAL_ANBERNIC_PATH)/package/anbernic/core/anbernic-system/anbernic-boot.conf $(BINARIES_DIR)/$(ANBERNIC_SYSTEM_SUBDIR)/anbernic-boot.conf

	# mounts
	mkdir -p $(TARGET_DIR)/boot $(TARGET_DIR)/overlay $(TARGET_DIR)/userdata
endef

$(eval $(generic-package))
